import { Parser, Language, type Node } from "web-tree-sitter";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import type { ParsedScript, ParsedScriptMember } from "../types.js";

const thisDir = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(thisDir, "../../grammars/tree-sitter-c_sharp.wasm");

let parser: Parser | null = null;

const MONOBEHAVIOUR_BASES = new Set(["MonoBehaviour", "NetworkBehaviour"]);

const SCRIPTABLE_OBJECT_BASES = new Set(["ScriptableObject"]);

const EDITOR_BASES = new Set([
  "Editor",
  "EditorWindow",
  "PropertyDrawer",
  "DecoratorDrawer",
  "AssetPostprocessor",
  "ScriptableWizard",
  "AssetImporter",
]);

// All Unity base classes that imply MonoBehaviour lineage
const ALL_MONOBEHAVIOUR = new Set([...MONOBEHAVIOUR_BASES]);

export async function initScriptParser(): Promise<void> {
  if (parser !== null) return;
  await Parser.init();
  const wasmBuffer = readFileSync(wasmPath);
  const lang = await Language.load(wasmBuffer);
  parser = new Parser();
  parser.setLanguage(lang);
}

export function getParser(): Parser | null {
  return parser;
}

export function parseScript(content: string): ParsedScript[] {
  if (!parser) {
    throw new Error("Script parser not initialized. Call initScriptParser() first.");
  }

  const tree = parser.parse(content);
  if (!tree) return [];

  const isGenerated = content.slice(0, 500).includes("<auto-generated>");
  const loc = content.split("\n").length;

  const results: ParsedScript[] = [];
  walkForTypeDeclarations(tree.rootNode, results, "", isGenerated, loc);

  tree.delete();
  return results;
}

type TypeKind = "class" | "struct" | "interface" | "enum";

const TYPE_NODE_KINDS: Record<string, TypeKind> = {
  class_declaration: "class",
  struct_declaration: "struct",
  interface_declaration: "interface",
  enum_declaration: "enum",
};

function walkForTypeDeclarations(
  node: Node,
  results: ParsedScript[],
  namespace: string,
  isGenerated: boolean,
  loc: number,
): void {
  for (const child of node.namedChildren) {
    if (child.type === "namespace_declaration") {
      const nameNode = child.childForFieldName("name");
      const ns = nameNode ? nameNode.text : "";
      const body = child.childForFieldName("body");
      if (body) {
        walkForTypeDeclarations(body, results, ns, isGenerated, loc);
      }
    } else if (child.type in TYPE_NODE_KINDS) {
      const parsed = parseTypeDeclaration(
        child,
        TYPE_NODE_KINDS[child.type],
        namespace,
        isGenerated,
        loc,
      );
      if (parsed) results.push(parsed);
    } else {
      // recurse into declaration lists, etc.
      walkForTypeDeclarations(child, results, namespace, isGenerated, loc);
    }
  }
}

function parseTypeDeclaration(
  node: Node,
  kind: TypeKind,
  namespace: string,
  isGenerated: boolean,
  loc: number,
): ParsedScript | null {
  const nameNode = node.childForFieldName("name");
  if (!nameNode) return null;
  const className = nameNode.text;

  // Extract base class and interfaces from base_list
  let baseClass = "";
  const interfaces: string[] = [];

  const baseListNode = node.namedChildren.find((c) => c.type === "base_list");
  if (baseListNode) {
    // base_list children: ':' followed by comma-separated type names
    const typeNames = baseListNode.namedChildren.filter(
      (c) => c.type === "identifier" || c.type === "generic_name" || c.type === "qualified_name",
    );

    for (let i = 0; i < typeNames.length; i++) {
      const typeName = typeNames[i].text.split("<")[0].trim(); // strip generics
      if (i === 0) {
        // Convention: first entry is base class if it doesn't start with I+uppercase
        if (!isInterfaceName(typeName)) {
          baseClass = typeName;
        } else {
          interfaces.push(typeName);
        }
      } else {
        interfaces.push(typeName);
      }
    }
  }

  const isMonoBehaviour = ALL_MONOBEHAVIOUR.has(baseClass);
  const isScriptableObject = SCRIPTABLE_OBJECT_BASES.has(baseClass);
  const isEditorScript = EDITOR_BASES.has(baseClass);

  // Extract members from the body
  const bodyNode = node.childForFieldName("body");
  const members: ParsedScriptMember[] = [];
  if (bodyNode) {
    extractMembers(bodyNode, members, kind);
  }

  return {
    className,
    kind,
    namespace,
    baseClass,
    interfaces,
    members,
    isMonoBehaviour,
    isEditorScript,
    isScriptableObject,
    isGenerated,
    loc,
  };
}

function isInterfaceName(name: string): boolean {
  return (
    name.length >= 2 &&
    name[0] === "I" &&
    name[1] === name[1].toUpperCase() &&
    name[1] !== name[1].toLowerCase()
  );
}

function extractMembers(body: Node, members: ParsedScriptMember[], typeKind: TypeKind): void {
  for (const child of body.namedChildren) {
    switch (child.type) {
      case "method_declaration":
        members.push(parseMethod(child, typeKind));
        break;
      case "field_declaration":
        members.push(...parseField(child));
        break;
      case "property_declaration":
        members.push(parseProperty(child, typeKind));
        break;
      case "constructor_declaration":
        members.push(parseConstructor(child));
        break;
      case "event_field_declaration":
        members.push(...parseEventField(child));
        break;
      default:
        // skip nested types, operators, indexers, etc.
        break;
    }
  }
}

function getModifiers(node: Node): string[] {
  return node.children
    .filter((c) => c.type === "modifier")
    .flatMap((m) => m.children.map((mc) => mc.text));
}

function getAccessModifier(modifiers: string[], defaultAccess: string): string {
  const accessMods = ["public", "private", "protected", "internal"];
  for (const mod of accessMods) {
    if (modifiers.includes(mod)) {
      // handle "protected internal" and "private protected"
      if (mod === "protected" && modifiers.includes("internal")) return "protected internal";
      if (mod === "private" && modifiers.includes("protected")) return "private protected";
      return mod;
    }
  }
  return defaultAccess;
}

function getAttributes(node: Node): string[] {
  const attrs: string[] = [];
  for (const child of node.children) {
    if (child.type === "attribute_list") {
      for (const attrNode of child.namedChildren) {
        if (attrNode.type === "attribute") {
          const nameNode = attrNode.childForFieldName("name");
          if (nameNode) attrs.push(nameNode.text);
        }
      }
    }
  }
  return attrs;
}

function getTypeText(node: Node | null): string {
  if (!node) return "";
  return node.text;
}

function parseParameters(paramListNode: Node | null): Array<{ name: string; type: string }> {
  if (!paramListNode) return [];
  const params: Array<{ name: string; type: string }> = [];

  for (const paramNode of paramListNode.namedChildren) {
    if (paramNode.type === "parameter") {
      const nameNode = paramNode.childForFieldName("name");
      const typeNode = paramNode.childForFieldName("type");
      if (nameNode) {
        params.push({
          name: nameNode.text,
          type: typeNode ? typeNode.text : "",
        });
      }
    }
  }
  return params;
}

function parseMethod(node: Node, typeKind: TypeKind): ParsedScriptMember {
  const modifiers = getModifiers(node);
  const defaultAccess = typeKind === "interface" ? "public" : "private";
  const access = getAccessModifier(modifiers, defaultAccess);
  const isStatic = modifiers.includes("static");

  const nameNode = node.childForFieldName("name");
  const returnsNode = node.childForFieldName("returns");
  const paramsNode = node.childForFieldName("parameters");
  const attributes = getAttributes(node);

  return {
    name: nameNode?.text ?? "",
    kind: "method",
    access,
    returnType: getTypeText(returnsNode),
    parameters: parseParameters(paramsNode),
    attributes,
    isStatic,
  };
}

function parseField(node: Node): ParsedScriptMember[] {
  const modifiers = getModifiers(node);
  const access = getAccessModifier(modifiers, "private");
  const isStatic = modifiers.includes("static");
  const attributes = getAttributes(node);

  // variable_declaration holds the type and variable_declarator(s)
  const varDecl = node.namedChildren.find((c) => c.type === "variable_declaration");
  if (!varDecl) return [];

  const typeNode = varDecl.childForFieldName("type");
  const returnType = getTypeText(typeNode);

  const declarators = varDecl.namedChildren.filter((c) => c.type === "variable_declarator");
  return declarators.map((declarator) => {
    const nameNode = declarator.childForFieldName("name");
    return {
      name: nameNode?.text ?? "",
      kind: "field" as const,
      access,
      returnType,
      parameters: [],
      attributes,
      isStatic,
    };
  });
}

function parseProperty(node: Node, typeKind: TypeKind): ParsedScriptMember {
  const modifiers = getModifiers(node);
  const defaultAccess = typeKind === "interface" ? "public" : "private";
  const access = getAccessModifier(modifiers, defaultAccess);
  const isStatic = modifiers.includes("static");
  const attributes = getAttributes(node);

  const nameNode = node.childForFieldName("name");
  const typeNode = node.childForFieldName("type");

  return {
    name: nameNode?.text ?? "",
    kind: "property",
    access,
    returnType: getTypeText(typeNode),
    parameters: [],
    attributes,
    isStatic,
  };
}

function parseConstructor(node: Node): ParsedScriptMember {
  const modifiers = getModifiers(node);
  const access = getAccessModifier(modifiers, "private");
  const isStatic = modifiers.includes("static");
  const attributes = getAttributes(node);

  const nameNode = node.childForFieldName("name");
  const paramsNode = node.childForFieldName("parameters");

  return {
    name: nameNode?.text ?? "",
    kind: "constructor",
    access,
    returnType: "",
    parameters: parseParameters(paramsNode),
    attributes,
    isStatic,
  };
}

function parseEventField(node: Node): ParsedScriptMember[] {
  const modifiers = getModifiers(node);
  const access = getAccessModifier(modifiers, "private");
  const isStatic = modifiers.includes("static");
  const attributes = getAttributes(node);

  const varDecl = node.namedChildren.find((c) => c.type === "variable_declaration");
  if (!varDecl) return [];

  const typeNode = varDecl.childForFieldName("type");
  const returnType = getTypeText(typeNode);

  const declarators = varDecl.namedChildren.filter((c) => c.type === "variable_declarator");
  return declarators.map((declarator) => {
    const nameNode = declarator.childForFieldName("name");
    return {
      name: nameNode?.text ?? "",
      kind: "event" as const,
      access,
      returnType,
      parameters: [],
      attributes,
      isStatic,
    };
  });
}
